train:
{
    mode: train
    coordinate: body_coord
    data_list:
    [   
        {name: BlackBird
        window_size: 100
        step_size: 10
        data_root: "c:\\Users\\Admin\\Music\\Air-IO\\data\\CustomData\\train"
        data_drive: ["sequence01", "sequence02"]
        },
    ]
    gravity: 9.81007
}

test:
{
    mode: test
    coordinate: body_coord
    data_list:
    [   
        {name: BlackBird
        window_size: 1000
        step_size: 10
        data_root: "c:\\Users\\Admin\\Music\\Air-IO\\data\\CustomData\\test"
        data_drive: ["sequence04"]
        },
    ]
    gravity: 9.81007
}

eval:
{    
    mode: evaluate
    coordinate: body_coord
    data_list:
    [{
        name: BlackBird
        window_size: 1000
        step_size: 20
        data_root: "c:\\Users\\Admin\\Music\\Air-IO\\data\\CustomData\\eval"
        data_drive: ["sequence03"]
        },
    ]
    gravity: 9.81007
}

inference:
{    
    mode: infevaluate
    coordinate: body_coord
    rot_type: None
    rot_path: PATH_TO_AIRIMU_NETOUTPUT
    data_list:
    [{
        name: BlackBird
        window_size: 1000
        step_size: 1000
        data_root: "c:\\Users\\Admin\\Music\\Air-IO\\data\\CustomData\\eval"
        data_drive: ["sequence03"]
        },
    ]
    gravity: 9.81007
}