train:
{
    mode: train
    coordinate: body_coord
    data_list:
    [   
        {name: BlackBird
        window_size: 1000
        step_size: 3
        data_root: "C:\Users\Admin\Music\Air-IO\data\Lakal"
        data_drive: [train]
        },
    ]
    gravity: 9.81007
}

test:
{
    mode: test
    coordinate: body_coord
    data_list:
    [   
        {name: BlackBird
        window_size: 1000
        step_size: 10
        data_root: "C:\Users\Admin\Music\Air-IO\data\Lakal"
        data_drive: [test]
        },
    ]
    gravity: 9.81007
}

eval:
{    
    mode: evaluate
    coordinate: body_coord
    data_list:
    [{
        name: BlackBird
        window_size: 1000
        step_size: 20
        data_root: "C:\Users\Admin\Music\Air-IO\data\Lakal"
        data_drive: [eval]
        },
    ]
    gravity: 9.81007

}


inference:
{    
    mode: infevaluate
    coordinate: body_coord
    rot_type: None
    rot_path: PATH_TO_AIRIMU_NETOUTPUT
    data_list:
    [{
        name: BlackBird
        window_size: 1000
        step_size: 1000
        data_root: "C:\Users\Admin\Music\Air-IO\data\Lakal"
        data_drive:  [eval]
        },
    ]
    gravity: 9.81007
}
